[theme]
primaryColor = "#13876f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f6f7"
textColor = "#24384b"
font = "sans serif"

[server]
headless = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false
